### ISSUE TITLE
Discord Core Build

### ISSUE THREAD

**Issue by khalosmoscato** [fac30/PRO02_Danielle_Jason_Khalos#7]
- [ ] Write a test function that creates a new Discord client
- [ ] Initialise the Discord bot
- [ ] Log in to Discord with the Discord.Client() constructor, client.login method & my Discord token
- [ ] Ensure that my bot initialises and logs into Discord successfully
- [ ] Set up a message event listener using client.on('messageCreate', callback)
- [ ] Respond to them with a “hello” message
- [ ] mock the process of sending responses back to the Discord channel, verifying that my bot formats and dispatches messages correctly & testing the message event listener’s functionality

**Comment by JasonWarrenUK** [comment]
Duplicated by other issues
